### ISSUE TITLE
Слои: преобразовать векторный слой ООПТ в тайловый

### ISSUE THREAD

**Issue by bolotoved** [nextgis/nextgisbio#41]
Преобразовать векторный слой ООПТ в тайловый для ускорения отрисовки. Заливка у полигонов должна быть прозрачной.
После преобразования в тайловый вид, слой ООПТ нужно сделать вкюченным по умолчанию.

**Comment by karavanjo** [comment]
Реализовано в https://github.com/nextgis/nextgisbio/issues/76
