### ISSUE TITLE
В логотипе NextGIS BIO буква O обрезана посередине

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgisbio#67]
![screenshot from 2016-05-11 16 49 56](https://cloud.githubusercontent.com/assets/866124/15177081/6d93ccae-1798-11e6-89c9-ee657a3a01a1.png)

**Comment by karavanjo** [comment]
Version 48.0.2564.82 Ubuntu 15.04 (64-bit) - все в порядке -
![loader](https://cloud.githubusercontent.com/assets/669999/20457504/05127ce6-ae9e-11e6-9535-e199b7a59032.gif)

@drnextgis можно версию браузера и ОС?

**Comment by simgislab** [comment]
у меня тоже все ок
