### ISSUE TITLE
не верная строка в setup.py

### ISSUE THREAD

**Issue by madw0lf** [nextgis/nextgisbio#68]
В setup.py есть строка
`README = open(os.path.join(here, 'README.txt')).read()`
установка прерывается с ошибкой:
`Command "python setup.py egg_info" failed with error code 1`
`File "/home/gis-adm/ngbio/nextgisbio/setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.txt')).read()
    IOError: [Errno 2] No such file or directory: '/home/gis-adm/ngbio/nextgisbio/README.txt'
`

лечится либо переименованием readme.md в readme.txt в папке или файле setup.py. ну, либо убрать эту зависимость в принципе.

**Comment by karavanjo** [comment]
Исправлено в https://github.com/nextgis/nextgisbio/commit/a01fe557b9d3c6254036bfe24fc45a98a63c25e6
