### ISSUE TITLE
где узнать/задать логин и пароль администратора?

### ISSUE THREAD

**Issue by madw0lf** [nextgis/nextgisbio#69]
я дико извиняюсь, но не нашел этого в документации.

**Comment by karavanjo** [comment]
В настоящий момент, первоначальное наполнение базы данных исходными данными, включая сведения о пользователях, осуществляется из набора .csv файлов. Поэтому задать эти параметры можно только при начальном импорте в файле пользователей.
Самих файлов в репозитории нет, так как в системе ugrabio содержатся данные, принадлежащие авторам, предоставившим их.
Я загружу пустые файлы с заголовками, что была понятна их структура. И у вас появится возможность заполнить их, применительно к вашим данным.

**Comment by karavanjo** [comment]
Директория, где расположены файлы для инициализации базы данных - https://github.com/nextgis/nextgisbio/tree/master/nextgisbio/initial_data.

**Comment by simgislab** [comment]
думаю это закрывает вопрос
