### ISSUE TITLE
Добавить страницу с табличным представлением карточек

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisbio#71]

**Comment by karavanjo** [comment]
Таблица добавлена:
![image](https://cloud.githubusercontent.com/assets/669999/21092532/0d2ca790-c05e-11e6-9ae3-db26486ed2b4.png)

Доступна из меню на главной странице авторизованным пользователям:
![image](https://cloud.githubusercontent.com/assets/669999/21092554/32b1c13a-c05e-11e6-8d6b-7a757904155e.png)

Так как поля для сохранения даты и времени создания карточки в БД не было, поле было создано и заполнено значением на 2016/12/11 для всех карточек.

Развернута на [стенде](http://system.ugrabio.ru/cards/table/).

**Comment by bolotoved** [comment]
Не понял, как экспортировать в CSV отобранные в таблице карточки. (ТЗ п.3.1.: "Также, на странице должен быть реализован экспорт выбранных строк таблицы в .csv файл. Набор полей в экспортированном файле должен быть полный.")
