### ISSUE TITLE
Реализовать механизм экспорта таблицы карточек в целевые форматы

### ISSUE THREAD

**Issue by karavanjo** [nextgis/nextgisbio#75]

**Comment by karavanjo** [comment]
Реализовано, развернуто на [основном стенде](http://system.ugrabio.ru/):
![75](https://cloud.githubusercontent.com/assets/669999/21517769/e743745e-ccf2-11e6-9643-dbc2858f4fcf.gif)

**Comment by bolotoved** [comment]
Экспорт в DOCX из табличного представления не работает, выдает ошибку "502 Bad Gateway".

**Comment by bolotoved** [comment]
В экспортированных карточках не все поля, например, нет поля "Дата".

**Comment by bolotoved** [comment]
Не реализована функция экспорта с панели просмотра карточки на главной странице для выбранной карточки (ТЗ п.2: "Экспорт карточек должен быть доступен: а) с панели просмотра карточки на главной странице для выбранной карточки; б) из таблицы карточек".

**Comment by karavanjo** [comment]
`Экспорт в DOCX из табличного представления не работает, выдает ошибку "502 Bad Gateway"`
Перенесено в https://github.com/nextgis/nextgisbio/issues/78

`Не реализована функция экспорта с панели просмотра карточки на главной странице для выбранной карточки (ТЗ п.2: "Экспорт карточек должен быть доступен: а) с панели просмотра карточки на главной странице для выбранной карточки; б) из таблицы карточек".)`
Перенесено в https://github.com/nextgis/nextgisbio/issues/79
